In [6]:
    x=1
x

1

# Welcome

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [3]:
matrix1 = [[1,2,3],[4,5,6]]
np_matrix = np.array(matrix1)
print(np_matrix)
print(type(np_matrix))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
range_arr = np.arange(11,23)
print(range_arr)

[11 12 13 14 15 16 17 18 19 20 21 22]


In [13]:
mul = np.zeros(shape=(2,3), dtype=int)
print(mul)
mul[0][0] = 1
print(mul)

[[0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 0 0]]


In [16]:
lin_Arr=np.linspace(0, 10, 8)
print(lin_Arr)

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [19]:
np.vectorize(lambda x: f"{x:.2f}")(lin_Arr)

array(['0.00', '1.43', '2.86', '4.29', '5.71', '7.14', '8.57', '10.00'],
      dtype='<U5')

In [20]:
np.around(lin_Arr, 2)

array([ 0.  ,  1.43,  2.86,  4.29,  5.71,  7.14,  8.57, 10.  ])

In [22]:
np.random.randint(0, 101, (2,5))

array([[92, 72, 67, 85,  7],
       [88, 41, 41, 42, 58]])

In [39]:
np.random.seed(42)
np.random.randint(0, 101, (2,5))

array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74]])

In [40]:
type([])

list

In [41]:
import array

# Creating an array of integers
arr = array.array('i', [1, 2, 3, 4, 5])
print(arr.itemsize)

4


In [2]:
arr1 = np.arange(0,25)
arr2 = arr1.reshape(5, 5)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
arr1.max()
arr2.max()

24

In [18]:
#arr1 = np.random.randint(0, 101, (5, 5))
arr0 = np.random.randint(0, 101, 25)
arr1 = arr0.reshape(5,5)
print(arr1)
print(arr1.max())
print(arr1.min())
print(arr1.argmax())
print(arr1.shape)
print(arr1.max(axis=1))

[[76 41 67 92 56]
 [82 59  4 43 93]
 [36 80 62  3 35]
 [61 25 20 49 35]
 [39  9 69 76 22]]
93
3
9
(5, 5)
[92 93 80 61 76]


In [25]:
arr1[-1,-1]
print(arr1[arr1.shape[0] - 1, arr1.shape[1] - 1])

22


In [34]:
arr1[:, 0:1] = 0
arr1

array([[ 0, 41, 67, 92, 56],
       [ 0, 59,  4, 43, 93],
       [ 0, 80, 62,  3, 35],
       [ 0, 25, 20, 49, 35],
       [ 0,  9, 69, 76, 22]])

In [44]:
arr1 = np.random.randint(0, 101, 25)
arr2 = arr1.copy()
arr2[0] = 1000
print(arr1)
print(arr2)
filter_Arr = arr1[arr1 > 50]
print(filter_Arr)
filter_Arr2 = arr1[(arr1 > 50) | (arr1 < 80)]
print(filter_Arr2)

[84 39 49 16 89 52 46 13 70 16 84 14 93 35 35 57 16 81 69 76 39 93  1 52
 86]
[1000   39   49   16   89   52   46   13   70   16   84   14   93   35
   35   57   16   81   69   76   39   93    1   52   86]
[84 89 52 70 84 93 57 81 69 76 93 52 86]
[84 39 49 16 89 52 46 13 70 16 84 14 93 35 35 57 16 81 69 76 39 93  1 52
 86]


In [53]:
list1 = [1,2,3]
list2 = [10, 10, 10]

np_list1 = np.array(list1)
np_list2 = np.array(list2)
new_arr = np_list1 + np_list2
print(new_arr)
print(np.concatenate((np_list1, np_list2)))
new_arr = new_arr + 10
print(new_arr)
print(new_arr.sum() - 11)
print(new_arr.mean())


[11 12 13]
[ 1  2  3 10 10 10]
[21 22 23]
55
22.0


In [56]:
arr1 = np.random.randint(0, 101, 6)
arr2 = arr1.reshape((2, 3))
print(arr2)
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))

[[14 21 61]
 [64 26 93]]
[ 78  47 154]
[ 96 183]


# PANDAS = Python Data Analysis Library

## Data frame - like SQL 
Excel manipulation <br />
Good for:<br />
prepare data<br />
clean data<br />
statistics - min, max, avg, mean, kobarians, shonut<br />
exploration - visual<br />
data sources - CSV, SQL. we will work with excel<br />
<b>pip install panda</b>

In [27]:
import numpy as np
import pandas as pd
# do pd. [tab] to see functions
# look in google for pandas.pydata.org/docs
# Pandas Series = like np.array
pd_series = pd.Series([10, 100, 15, 35]) # we can put diff types but then the Series will be object. not recommended
np_array = np.array([10, 100, 15, 35])
print(np_array)
print(pd_series)
print(type(pd_series))
# we get a table with index-value, like dictionary. this is thee diff
# we can change from default numbers to seomthing else
data = [1776, 1867, 1821]
label_index = ['USA', 'CANADA', 'MEXICO']
pd_series = pd.Series(data, label_index)
print(pd_series)
print(pd_series['USA']) # this is a unique feature of Pandas
#print(pd_series[0]) #this will show a Warning since the index is string and will not work in future version # use iloc
# see below how to print index 0 using .keys()

# can we append?
# Create an initial Series
original_series = pd.Series([1, 2, 3])
# Append an item (4) to the Series using pd.concat
new_series = pd.concat([original_series, pd.Series([4])], ignore_index=True)
print(new_series)

dict1 = {'USA': 1776, 'CANADA': 1867, 'MEXICO': 1821}
pd_ser_dict = pd.Series(dict1)
print(pd_ser_dict)

pd_keys = pd_series.keys()
print(pd_keys)
print(type(pd_keys))
print(pd_keys[0])
print(pd_keys.size)
print(pd_series[pd_keys[0]])

second = {'Brazil': 1768, 'CHINA': 200, 'USA': 100}
second_ser = pd.Series(second)
concat_ser = pd_ser_dict + second_ser #where it does not appear in both it becomes NaN
print(concat_ser)
concat_ser2 = pd_ser_dict.add(second_ser, fill_value=0) # without fill_value=0 it will look the 2 lines ago
print(concat_ser2)

[ 10 100  15  35]
0     10
1    100
2     15
3     35
dtype: int64
<class 'pandas.core.series.Series'>
USA       1776
CANADA    1867
MEXICO    1821
dtype: int64
1776
0    1
1    2
2    3
3    4
dtype: int64
USA       1776
CANADA    1867
MEXICO    1821
dtype: int64
Index(['USA', 'CANADA', 'MEXICO'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
USA
3
1776
Brazil       NaN
CANADA       NaN
CHINA        NaN
MEXICO       NaN
USA       1876.0
dtype: float64
Brazil    1768.0
CANADA    1867.0
CHINA      200.0
MEXICO    1821.0
USA       1876.0
dtype: float64
